version: "3"

services: 
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run dev
    networks:
      - db
    restart: always
  searchNet:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - db

networks:
  db:
    driver: bridge